# اسم التطبيق
spring.application.name=spring-blog-shop

# إعدادات قاعدة البيانات
spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_tp1
spring.datasource.username=root
spring.datasource.password=


# إعدادات JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# إعدادات Thymeleaf
spring.thymeleaf.cache=false
